spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      # 클라이언트와 카프카 클러스터 간의 통신에 사용될 보안 프로토콜
      security.protocol: SASL_SSL

      # SASL 인증 시 사용할 메커니즘 지정 (PLAIN: 사용자의 이름과 비밀번호를 전송하는 방법)
      sasl.mechanism: PLAIN

      # SASL_SSL 인증을 고정하는 역할 (API KEY와 시크릿 값을 넣어서 인증 활성화)
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";

      # SASL_SSL 인증을 위해 인증서 위치 지정 (로컬 환경이기 때문에 필요하다.)
      ssl.truststore.location: /Users/kimbyung-gwan/workspace/tool/docker/kafka/config/certs/kafka.truststore.jks
      ssl.truststore.password: password
      ssl.truststore.type: JKS
      ssl.keystore.location: /Users/kimbyung-gwan/workspace/tool/docker/kafka/config/certs/kafka.keystore.jks
      ssl.keystore.password: password
      ssl.keystore.type: JKS

      # 주어진 호스트 이름에 대해서 모든 IP 주소를 조회하고 사용하라고 지시하는 설정
      # 네트워크 파티션이나 DNS 문제가 발생했을 때 다른 방법들보다 카프카 클러스터의 연결 가능성을 높여준다.
      client.dns.lookup: use_all_dns_ips

      # 프로듀가 브로커로부터 메세지 전송에 대해 어느정도까지 확인을 받을 것인지 결정하는 설정
      # all은 모든 레플리카가 성공적으로 복제했다는 확인을 받은 후에만 메세지 전송이 성공했다는 응답을 받기 때문에 데이터 손실이 가장 적다.
      # 물론 그만큼 전송속도가 느리지만 신뢰성이 중요하기 때문에 all로 설정한다.
      producer-properties.acks: all

      # 존재하지않는 토픽에 대한 메시지를 받을 때 자동으로 해당 토픽을 생성할지 여부를 결정하는 설정
      # 불필요한 토픽 생성을 방지하고자 false 로 설정한다.
      auto-create-topics: false

  cloud:
#    function:
#      definition: send;wallet;ledger
    stream:
      kafka:
        # 카프카 클러스터와 연결하기 위한 바인딩 설정
        # 바인딩을 위한 함수는 직접 구현해야 한다.
#        bindings:
#          send-out-0:
#            producer:
#              record-metadata-channel: payment-result
#
#          wallet-in-0:
#            consumer:
#              configuration:
#                isolation:
#                  level: read_committed
#              enable-dlq: true
#              dlq-name: wallet_payment_dlq
#
#          ledge-in-0:
#            consumer:
#              configuration:
#                isolation:
#                  level: read_committed
#              enable-dlq: true
#              dlq-name: ledge_payment_dlq
#
      bindings:
        # destination: 목적지는 카프카 토픽 (payment)으로 설정한다.
        # group: 메세지를 그룹별로 처리할 수 있다.
        consume-in-0:
          destination: payment
          group: payment-service
#        send-out-0:
#          destination: payment
#          group: payment-service
#        wallet-in-0:
#          destination: wallet
#          group: payment-service
#        ledge-in-0:
#          destination: ledge
#          group: payment-service

logging:
  level:
    org:
      springframework:
        web: DEBUG
        r2dbc: DEBUG
        transaction: DEBUG

PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com

management:
  endpoints:
    web:
      exposure:
        include: bindings